routes/admin.php
<?php

Route::group(['middleware' => ['auth','role:1'], 'prefix' => 'admin'], function(){
    Route::get('dashboard', 'Admin\DashboardController@index')->name('admin.dashboard');
    Route::resource('proveedoresAdmin', 'Admin\DashboardController');
    Route::get('proveedoresAdminPend', 'Admin\DashboardController@proveedoresAdminPend')->name('admin.proveedoresAdminPend');
    Route::get('proveedoresAdminAutorizado', 'Admin\DashboardController@proveedoresAdminAutorizado')->name('admin.proveedoresAdminAutorizado');
    Route::get('proveedoresAdminRechazado', 'Admin\DashboardController@proveedoresAdminRechazado')->name('admin.proveedoresAdminRechazado');
    Route::resource('usuarios', 'Admin\UsuarioController');
    Route::get('listUser', 'Admin\UsuarioController@listUser')->name('admin.listUser');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

require __DIR__ . '/admin.php';
require __DIR__ . '/clientes.php';
require __DIR__ . '/proveedores.php';

app/Http/Controllers/Admin/UsuarioController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Roles;
use DataTables;

class UsuarioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rol = Roles::all();
        return view('admin.usuario.index', compact('rol'));
    }

    public function listUser(Request $request)
    {
        if ($request->ajax()) {
            $data = User::all();
            return Datatables::of($data)
                ->editColumn('role', function ($user) {
                    return $user->role->nombre;
                })
                ->editColumn('proveedores', function($user){
                    return $user->proveedores->count();
                 })             
                ->addIndexColumn()
                ->addColumn('btn', 'admin.usuario.opciones')
                ->rawColumns(['btn'])
                ->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required',
            'role_id' => 'required',
        ]
    );
   $usuario = User::create([
        'name' => $request->get('name'),
        'ap_paterno' => $request->get('ap_paterno'),
        'ap_materno' => $request->get('ap_materno'),
        'email' => $request->get('email'),
        'password' => bcrypt($request->get('password')),
        'role_id' => $request->get('role_id'),
    ]);

    alert()->success('El usuario ha sido creado correctamente.', 'Usuario creado');
    return redirect()->route('usuarios.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required',
            'ap_paterno' => 'required',
            'ap_materno' => 'required',
            'email' => 'required',
            'role_id' => 'required'
        ]);
        $usuario = User::find($id)->update($request->except(['_method', '_token']));
        alert()->success('El usuario ha sido actualizado correctamente.', 'Usuario actualizada');
        return redirect()->route('usuarios.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/usuario/create.blade.php
<div class="modal" id="crear_usuario">
    <div class="modal__content modal__content--xl">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                Creacion de nuevos usuarios
            </h2>
        </div>
        <form method="POST" action="{{ route('usuarios.store') }}"  role="form">
            {{ csrf_field() }}
        <div class="p-5 grid grid-cols-12 gap-4 row-gap-3">
        	<div class="col-span-12 sm:col-span-4 @if ($errors->has('name')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="name">Nombre</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="name" id="name" aria-describedby="helpNombre">
                <span id="helpNombre" class="help-block">
                    @if ($errors->has('name'))
                        @foreach($errors->get('name') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-4 @if ($errors->has('ap_paterno')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="ap_paterno">Apellido paterno</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="ap_paterno" id="ap_paterno" aria-describedby="helpAppaterno">
                <span id="helpAppaterno" class="help-block">
                    @if ($errors->has('ap_paterno'))
                        @foreach($errors->get('ap_paterno') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-4 @if ($errors->has('ap_materno')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="ap_materno">Apellido materno</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="ap_materno" id="ap_materno"  aria-describedby="helpApmaterno">
                <span id="helpApmaterno" class="help-block">
                    @if ($errors->has('ap_materno'))
                        @foreach($errors->get('ap_materno') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-12">
            </div>
             <div class="col-span-12 sm:col-span-4 @if ($errors->has('email')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="email">Email</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="email" id="email" aria-describedby="helpemail">
                <span id="helpemail" class="help-block">
                    @if ($errors->has('email'))
                        @foreach($errors->get('email') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-4 @if ($errors->has('password')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="password">Contraseña</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="password" id="password" aria-describedby="helpPassword">
                <span id="helpPassword" class="help-block">
                    @if ($errors->has('password '))
                        @foreach($errors->get('password ') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-4 @if ($errors->has('role_id')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="role_id">Rol</label>
                 <select class="input w-full border mt-2 flex-1" id="role_id" name="role_id">
                 	 	<option value="">Selecciona una opcion</option>
                    @foreach($rol as $roles)
                    	<option value="{{$roles->id}}">{{$roles->nombre}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-span-12 sm:col-span-12">
            </div>
        </div>
        <div class="px-5 py-3 text-right border-t border-gray-200">
            <button type="button" data-dismiss="modal" class="button w-20 border text-gray-700 mr-1">Cancelar</button>
            <button class="button w-20 bg-theme-1 text-white">Guardar</button>
        </div>
        </form>
    </div>
</div>

resources/views/admin/usuario/edit.blade.php
<div class="modal" id="edit-usuario{{$id}}">
    <div class="modal__content modal__content--xl">
        <div class="flex items-center px-5 py-5 sm:py-3 border-b border-gray-200">
            <h2 class="font-medium text-base mr-auto">
                Edicion del usuario: {{$name}}
            </h2>
        </div>
        {!! Form::open(['route' => ['usuarios.update', $id], 'method' => 'PUT']) !!}
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="PUT">
        <div class="p-5 grid grid-cols-12 gap-4 row-gap-4">
            <div class="col-span-12 sm:col-span-3 @if ($errors->has('name')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="name">Nombre:</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="name" id="name" value="{{$name}}" aria-describedby="helpnombre" required>
                <span id="helpnombre" class="help-block">
                    @if ($errors->has('name'))
                        @foreach($errors->get('name') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-4 @if ($errors->has('ap_paterno')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="ap_paterno">Ap. paterno:</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="ap_paterno" id="ap_paterno" aria-describedby="helpap_paterno" value="{{$ap_paterno}}" required>
                <span id="ap_paterno" class="help-block">
                    @if ($errors->has('helpap_paterno'))
                        @foreach($errors->get('ap_paterno') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-4 @if ($errors->has('ap_materno')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="ap_materno">Ap. materno:</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="ap_materno" id="ap_materno"  aria-describedby="helpap_materno" value="{{$ap_materno}}" required>
                <span id="helpap_materno" class="help-block">
                    @if ($errors->has('ap_materno'))
                        @foreach($errors->get('ap_materno') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-12">
            </div>
            <div class="col-span-12 sm:col-span-6 @if ($errors->has('email')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="email">Email:</label>
                <input type="text" class="input w-full border mt-2 flex-1" name="email" id="email"  aria-describedby="helpemail" value="{{$email}}" required>
                <span id="helpemail" class="help-block">
                    @if ($errors->has('email'))
                        @foreach($errors->get('email') as $message)
                            @if(!$loop->first) / @endif
                            {{ $message }}
                        @endforeach
                    @endif
                </span>
            </div>
            <div class="col-span-12 sm:col-span-6 @if ($errors->has('role_id')) has-error @endif">
                <label class="font-medium text-base mr-auto" for="role_id">Rol:</label>
                <select class="input w-full border mt-2 flex-1" id="role_id" name="role_id">
                @php $rol = \App\Roles::all(); @endphp
                    @foreach($rol as $roles)
                    	<option value="{{$roles->id}}" @if($role_id == $roles->id) selected="selected" @endif>{{$roles->nombre}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-span-12 sm:col-span-12">
            </div>
        </div>
        <div class="px-5 py-3 text-right border-t border-gray-200">
            <button type="button" data-dismiss="modal" class="button w-20 border text-gray-700 mr-1">Cancelar</button>
            <button class="button w-20 bg-theme-1 text-white">Guardar</button>
        </div>
        {!! Form::close()!!}
    </div>
</div>

resources/views/admin/usuario/index.blade.php
@extends('layouts/app')
@section('title', 'Usuario')
@section('content')
<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Usuarios
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0">
        <a class="button text-white bg-theme-1 shadow-md mr-2" href="javascript:;" data-toggle="modal" data-target="#crear_usuario" >Crear usuario</a>
        @include('admin.usuario.create')
    </div>
</div><br><br>
 <div class="tab-content__pane active" id="usuarios">
	<div class="intro-y datatable-wrapper overflow-x-auto">
	    <table class="table table-report table-report--bordered display datatable w-full" id="usuario">
	        <thead>
	            <tr>
	                <th class="border-b-2 whitespace-no-wrap">Id</th>
                    <th class="border-b-2 whitespace-no-wrap">Nombre</th>
                    <th class="border-b-2 whitespace-no-wrap">Ap. paterno</th>
                    <th class="border-b-2 whitespace-no-wrap">Ap. materno</th>
	                <th class="border-b-2 text-center whitespace-no-wrap">Email</th>
	                <th class="border-b-2 text-center whitespace-no-wrap">Rol</th>
	                <th class="border-b-2 text-center whitespace-no-wrap">Proveedores creados</th>
	                <th class="border-b-2 text-center whitespace-no-wrap">Opciones</th>
	            </tr>
	        </thead>
	        <tbody>

	        </tbody>
	    </table>
	</div>
</div>
@endsection
@section('scripts_ready')
<script type="text/javascript">
    $(function () {
      $('#usuario').DataTable().destroy();
      var table = $('#usuario').DataTable({
          processing: true,
          serverSide: true,
        ajax: "{{ route('admin.listUser') }}",
        columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'ap_paterno', name: 'ap_paterno'},
            {data: 'ap_materno', name: 'ap_materno'},
            {data: 'email', name: 'email',class: "text-center border-b"},
            {data: 'role', name: 'role', class: "text-center border-b"},
            {data: 'proveedores', name: 'proveedores', class: "text-center border-b"},
            {data: 'btn', name: 'btn', class: "text-center border-b"},
        ],
            "language": {
                "info": "_TOTAL_ registros",
                "search": "Buscar",
                "paginate": {
                    "next": "Siguiente",
                    "previous": "Anterior",
                },
                "lengthMenu": 'Mostrar <select >'+
                            '<option value="10">10</option>'+
                            '<option value="30">30</option>'+
                            '<option value="-1">Todos</option>'+
                            '</select> registros',
                "loadingRecords": "Cargando...",
                "processing": "Procesando...",
                "emptyTable": "No hay datos",
                "zeroRecords": "No hay coincidencias",
                "infoEmpty": "",
                "infoFiltered": ""
            }
    });
  });
</script>
@endsection

resources/views/admin/usuario/opciones.blade.php
<div class="flex justify-center items-center">
    <a class="flex items-center text-theme-6" href="javascript:;" data-toggle="modal" data-target="#edit-usuario{{$id}}" value="{{$id}}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Editar </a>
    @include('admin.usuario.edit')
</div>